import { StyleSheet } from 'react-native';

export const CORAL = '#E1583B';
export const CREAM = '#FBF5EF';
export const CARD = '#FFFFFF';
export const INK = '#2B2019';
export const MUTED = '#7C6E63';
export const BORDER = '#EBE0D5';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: CREAM },
  flex: { flex: 1, paddingHorizontal: 20, backgroundColor: CREAM },
  flexBare: { flex: 1, backgroundColor: CREAM },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: CREAM },
  screen: { flex: 1, justifyContent: 'center', paddingHorizontal: 24, gap: 12, backgroundColor: CREAM },
  scroll: { padding: 20, gap: 14, backgroundColor: CREAM },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingHorizontal: 20,
  },
  headerInPad: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  rowGap: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  flexItem: { flex: 1 },
  title: { fontSize: 24, fontWeight: '800', color: INK, letterSpacing: -0.5 },
  subtitle: { color: MUTED, fontSize: 14 },
  spinner: { marginTop: 24 },
  list: { gap: 12, paddingVertical: 16, paddingHorizontal: 20 },
  listInPad: { gap: 12, paddingVertical: 16 },
  fieldGap: { gap: 6 },
  fieldLabel: { fontSize: 13, fontWeight: '600', color: INK },
  input: {
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: INK,
  },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  pill: {
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  pillActive: { backgroundColor: CORAL, borderColor: CORAL },
  pillText: { color: INK, fontSize: 13 },
  pillTextActive: { color: '#fff', fontSize: 13, fontWeight: '600' },
  toggleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#c9bcae',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxOn: { backgroundColor: CORAL, borderColor: CORAL },
  checkMark: { color: '#fff', fontSize: 14 },
  button: {
    backgroundColor: CORAL,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
    shadowColor: CORAL,
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  buttonDisabled: { opacity: 0.4 },
  buttonText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  buttonOutline: {
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  buttonOutlineText: { color: INK, fontWeight: '600' },
  link: { color: CORAL, fontWeight: '600' },
  error: { color: '#C0392B', fontSize: 14 },
  card: {
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    borderRadius: 16,
    padding: 16,
    gap: 4,
  },
  cardUnread: { borderColor: CORAL, backgroundColor: '#FFF4EF' },
  cardTitle: { fontSize: 17, fontWeight: '700', color: INK },
  meta: { color: MUTED, fontSize: 13 },
  navRow: { flexWrap: 'wrap', marginTop: 4, marginBottom: 4 },
  badge: { fontSize: 12, fontWeight: '700' },
  receiptRef: { color: MUTED, fontSize: 11, marginTop: 2 },
  groupBox: { marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderColor: BORDER, gap: 6 },
  groupMember: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  groupHint: { color: MUTED, fontSize: 12 },
  pickerMap: { height: 220, borderRadius: 14, overflow: 'hidden', borderWidth: 1, borderColor: BORDER },
  bubbleRow: { flexDirection: 'row', marginVertical: 3 },
  bubble: { maxWidth: '80%', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 8 },
  bubbleMine: { backgroundColor: CORAL, borderBottomRightRadius: 4 },
  bubbleOther: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: BORDER,
    borderBottomLeftRadius: 4,
  },
  bubbleName: { color: MUTED, fontSize: 11, fontWeight: '600', marginBottom: 2 },
  bubbleText: { color: INK, fontSize: 14 },
  bubbleTextMine: { color: '#fff', fontSize: 14 },
  mapContainer: { flex: 1, backgroundColor: CREAM },
  mapHeader: { paddingHorizontal: 20 },
  mapWrap: { flex: 1 },
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: CARD,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderTopWidth: 1,
    borderColor: BORDER,
    padding: 20,
    gap: 4,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: -3 },
  },
  sheetItem: { gap: 6, marginTop: 10 },
  tabBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: BORDER,
    backgroundColor: CARD,
    paddingTop: 8,
    paddingBottom: 10,
    paddingHorizontal: 4,
  },
  tabItem: { flex: 1, alignItems: 'center', gap: 2, paddingVertical: 4 },
  tabLabel: { fontSize: 11, color: MUTED, fontWeight: '600' },
  tabLabelActive: { color: CORAL, fontWeight: '700' },
  tabIcon: { fontSize: 16, color: MUTED },
  tabIconActive: { color: CORAL },
  chipScroll: { paddingHorizontal: 20, paddingVertical: 8, gap: 8 },
  sectionPad: { paddingHorizontal: 20, gap: 8 },
  unreadDot: {
    position: 'absolute',
    top: -2,
    right: 18,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: CORAL,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  unreadDotText: { color: '#fff', fontSize: 10, fontWeight: '700' },
});
